# services to handle doctrine extensions
# import it in config/packages/doctrine_extensions.yaml
services:
  # Doctrine Extension listeners to handle behaviors
  gedmo.mapping.driver.attribute:
    class: Gedmo\Mapping\Driver\AttributeReader
  Gedmo\Timestampable\TimestampableListener:
    tags:
      - { name: doctrine.event_listener, event: 'prePersist' }
      - { name: doctrine.event_listener, event: 'onFlush' }
      - { name: doctrine.event_listener, event: 'loadClassMetadata' }
    calls:
      - [ setAnnotationReader, [ "@gedmo.mapping.driver.attribute" ] ]

  Gedmo\Blameable\BlameableListener:
    tags:
      - { name: doctrine.event_listener, event: 'prePersist' }
      - { name: doctrine.event_listener, event: 'onFlush' }
      - { name: doctrine.event_listener, event: 'loadClassMetadata' }
    calls:
      - [ setAnnotationReader, [ "@gedmo.mapping.driver.attribute" ] ]