INSERT INTO `size` (`name`, `min_height`, `max_height`, `min_width`, `max_width`, `note`) VALUES
('A3+', 298, 353, 421, 500, NULL),
('A3', 297, 297, 420, 420, NULL),
('A3-', 251, 296, 354, 421, NULL),
('A4+', 211, 250, 298, 353, NULL),
('A4', 210, 210, 297, 297, NULL),
('A4-', 177, 209, 251, 296, 'Carnet de marches, 2 par feuille'),
('A5+', 149, 176, 211, 250, NULL),
('A5', 148, 148, 210, 210, NULL),
('A5-', 0, 147, 0, 209, 'Carnet de marches');

INSERT INTO `instrumentation` (`id`, `name`, `note`) VALUES
(NULL, 'Symphonie', 'Pour cordes, cuivres et bois, voix séparées par registres'),
(NULL, 'Harmonie', 'Pour cuivres et bois, voix séparées par registres'),
(NULL, 'Brass band', 'Pour cuivres uniquement, voix séparées par registres'),
(NULL, 'Flexible', 'Voix numérotées, séparées par transposition (ut, si♭, mi♭, fa) et plusieurs instruments pour une même partition');

INSERT INTO `status` (`id`, `name`) VALUES
('complete', 'Complet'),
('lost', 'Perdu'),
('lent', 'Prêté'),
('incomlete', 'Incomplet'),
('unstamped', 'Originaux non marqués');

INSERT INTO `instrument` (`family`, `name`, `key`, `common`) VALUES
('wood', 'Piccolo', 'd_flat', true),
('wood', 'Accordéon', null, false),
('percussion', 'Almglocken', null, false),
('voice', 'Alto', null, false),
('voice', 'Altos', null, false),
('wood', 'Anche libre', null, false),
('string', 'Archiluth', null, false),
('wood', 'Aulochrome', null, false),
('string', 'Balalaïka', null, false),
('string', 'Balalaïka Alto', null, false),
('string', 'Balalaïka Basse', null, false),
('string', 'Balalaïka Contrebasse', null, false),
('string', 'Balalaïka Piccolo', null, false),
('string', 'Balalaïka Prima', null, false),
('string', 'Balalaïka Secunda', null, false),
('wood', 'Bandonéon', null, false),
('string', 'Banjo', null, false),
('string', 'Banjo Irlandais Ténor', null, false),
('string', 'Banjo ténor', null, false),
('voice', 'Baryton', null, false),
('string', 'Basse', null, false),
('string', 'Basse acoustique', null, false),
('string', 'Basse électrique', null, false),
('string', 'Basse électrique fretless', null, false),
('string', 'Basse électrique à 5 cordes', null, false),
('string', 'Basse électrique à 5 cordes (Ténor)', null, false),
('string', 'Basse électrique à 6 cordes', null, false),
('wood', 'Basson', null, true),
('percussion', 'Batterie', null, false),
('string', 'Berda', null, false),
('percussion', 'Bols chantants', null, false),
('percussion', 'Bongos', null, false),
('string', 'Bouzouki', null, false),
('string', 'Bouzouki (3 chœurs)', null, false),
('string', 'Bouzouki (4 chœurs)', null, false),
('string', 'Bugarija', null, false),
('percussion', 'Cabasa', null, false),
('percussion', 'Caisse claire', null, true),
('percussion', 'Caisse claire de concert', null, false),
('percussion', 'Carillon en bambou', null, false),
('percussion', 'Carillon en bois', null, false),
('percussion', 'Carillon en coquillages', null, false),
('percussion', 'Carillon en métal', null, false),
('percussion', 'Carillon en verre', null, false),
('percussion', 'Carillons', null, false),
('percussion', 'Castagnettes', null, false),
('percussion', 'Castagnettes métalliques', null, false),
('string', 'Cavaquinho', null, false),
('wood', 'Cervelas', null, false),
('wood', 'Chalemie Alto', null, false),
('wood', 'Chalemie Grande Basse', null, false),
('wood', 'Chalemie Sopranino', null, false),
('wood', 'Chalemie Soprano', null, false),
('wood', 'Chalemie Ténor', null, false),
('wood', 'Chalumeau', null, false),
('wood', 'Chalumeau Alto', null, false),
('wood', 'Chalumeau Basse', null, false),
('wood', 'Chalumeau Sopranino', null, false),
('wood', 'Chalumeau Soprano', null, false),
('wood', 'Chalumeau Ténor', null, false),
('percussion', 'Charleston', null, false),
('percussion', 'Chaînes', null, false),
('wood', 'Chofar', null, false),
('voice', 'Chorale', null, false),
('voice', 'Chœurs', null, false),
('brass', 'Cimbasso', null, false),
('brass', 'Clairon', null, false),
('brass', 'Clairon Alto', null, false),
('brass', 'Clairon Contrebasse', null, false),
('brass', 'Clairon Euphonium', null, false),
('brass', 'Clairon Mellophone', null, false),
('brass', 'Clairon Soprano', null, false),
('percussion', 'Claquement de mains', null, false),
('percussion', 'Claquement de doigts', null, false),
('wood', 'Clarinette', null, true),
('wood', 'Clarinette Alto', 'e_flat', false),
('wood', 'Clarinette Basse', 'b_flat', false),
('wood', 'Clarinette Basse', 'a', false),
('wood', 'Clarinette Contre-Alto', 'e_flat', false),
('wood', 'Clarinette Contrebasse', 'b_flat', false),
('wood', 'Clarinette de basset', 'f', false),
('wood', 'Clarinette', 'c', false),
('wood', 'Clarinette', 'e_flat', false),
('wood', 'Clarinette', 'd', false),
('wood', 'Clarinette', 'b_flat', true),
('wood', 'Clarinette', 'g', false),
('wood', 'Clarinette piccolo', 'a_flat', false),
('wood', 'Clarinette soprano', 'e_flat', false),
('wood', 'Clarinette-Heckelphone', 'b_flat', false),
('string', 'Clavecin', null, false),
('percussion', 'Claves', null, false),
('string', 'Clavicorde', null, false),
('string', 'Clavinet', null, false),
('percussion', 'Cloche', null, false),
('percussion', 'Cloche plaque', null, false),
('percussion', 'Cloches à mains', null, false),
('percussion', 'Cloches tubulaires', null, false),
('percussion', 'Clochettes', null, false),
('wood', 'Concertina', null, false),
('wind', 'Conque', null, false),
('voice', 'Contre-alto', null, false),
('voice', 'Contre-ténor', null, false),
('string', 'Contrebasse', null, false),
('voice', 'Contrebasses', null, false),
('wood', 'Contrebasson', null, false),
('wood', 'Cor anglais', null, false),
('brass', 'Cor baryton', null, false),
('wood', 'Cor de basset', null, false),
('wood', 'Cor des Alpes', null, false),
('brass', 'Cor', 'c', false),
('brass', 'Cor aigu', 'c', false),
('brass', 'Cor', 'f', false),
('brass', 'Cor', 'a', false),
('brass', 'Cor', 'a_flat', false),
('brass', 'Cor', 'e', false),
('brass', 'Cor', 'e_flat', false),
('brass', 'Cor', 'd', false),
('brass', 'Cor', 'b_flat', false),
('brass', 'Cor grave', 'b_flat', false),
('brass', 'Cor', 'g', false),
('brass', 'Cor postal', null, false),
('brass', 'Cor viennois', null, false),
('wood', 'Cornemuse', null, false),
('wood', 'Cornemuse Alto', null, false),
('wood', 'Cornemuse Basse', null, false),
('wood', 'Cornemuse Soprano', null, false),
('wood', 'Cornemuse Ténor', null, false),
('brass', 'Cornet', null, true),
('brass', 'Cornet Alto', null, false),
('brass', 'Cornet Soprano', null, false),
('brass', 'Cornet Ténor', null, false),
('brass', 'Cornet', 'c', false),
('brass', 'Cornet', 'a', false),
('brass', 'Cornet', 'e_flat', false),
('brass', 'Cornet', 'b_flat', true),
('wood', 'Cornettino', null, false),
('wood', 'Cromorne', null, false),
('percussion', 'Crotales', null, false),
('percussion', 'Crécelle', null, false),
('percussion', 'Cuica', null, false),
('percussion', 'Cymbale', null, false),
('percussion', 'Cymbale chinoise', null, false),
('percussion', 'Cymbale crash', null, false),
('percussion', 'Cymbale ride', null, false),
('percussion', 'Cymbale splash', null, false),
('percussion', 'Cymbales', null, true),
('percussion', 'Cymbales à doigts', null, false),
('percussion', 'Célesta', null, false),
('wood', 'Danso', null, false),
('wood', 'Dessus de viole', null, false),
('wood', 'Didgeridoo', null, false),
('wood', 'Dizi', null, false),
('wood', 'Dizi', 'c', false),
('wood', 'Dizi', 'f', false),
('wood', 'Dizi', 'a', false),
('wood', 'Dizi', 'e', false),
('wood', 'Dizi', 'g', false),
('wood', 'Doudouk', null, false),
('wood', 'Doudouk Basse', 'a', false),
('wood', 'Doudouk', 'c', false),
('wood', 'Doudouk', 'f', false),
('wppd', 'Doudouk', 'a', false),
('wood', 'Doudouk', 'e', false),
('wood', 'Doudouk', 'b', false),
('wood', 'Doudouk', 'b_flat', false),
('wood', 'Douçaine', null, false),
('string', 'Dulcimer', null, false),
('brass', 'Dungchen', null, false),
('percussion', 'Enclume', null, false),
('string', 'Erhu', null, false),
('brass', 'Euphonium', null, true),
('brass', 'Euphonium', 'b_flat', true),
('voice', 'Femmes', null, false),
('wood', 'Fifre', 'b_flat', false),
('wood', 'Fiscorn', null, false),
('wood', 'Flageolet', null, false),
('wood', 'Flageolet anglais', null, false),
('wood', 'Flageolet français', null, false),
('percussion', 'Flexatone', null, false),
('wood', 'Flûte', null, true),
('wood', 'Flûte aiguë', null, false),
('wood', 'Flûte soprano', null, false),
('wood', 'Flûte sub-contralto', null, false),
('wood', 'Flûte alto', null, false),
('wood', 'Flûte basse', null, false),
('wood', 'Flûte contre-alto', null, false),
('wood', 'Flûte contrebasse', null, false),
('wood', 'Flûte octobasse', null, false),
('wood', 'Flûte hyperbasse', null, false),
('wood', 'Flûte Sopranino', 'c', false),
('wood', 'Flûte de Pan', null, false),
('wood', 'Flûte irlandaise', null, false),
('wood', 'Flûte à bec', null, false),
('wood', 'Flûte à bec Contrebasse', null, false),
('wood', 'Flûte à bec Soubasse', null, false),
('wood', 'Flûte à bec Ténor', null, false),
('wood', 'Flûte à bec alto', null, false),
('wood', 'Flûte à bec basse', null, false),
('wood', 'Flûte à bec sopranino', 'f', false),
('wood', 'Flûte à bec soprano', null, false),
('percussion', 'Fouet', null, false),
('voice', 'Garçon soprano', null, false),
('wood', 'Gemshorn', null, false),
('wood', 'Gemshorn Alto', null, false),
('wood', 'Gemshorn Basse', null, false),
('wood', 'Gemshorn Soprano', null, false),
('wood', 'Gemshorn Ténor', null, false),
('percussion', 'Glockenspiel', null, true),
('percussion', 'Gong', null, false),
('percussion', 'Gongs accordés', null, false),
('percussion', 'Grosse caisse de concert', null, true),
('string', 'Guitare', null, false),
('string', 'Guitare Alto', null, false),
('string', 'Guitare Alto à 11 cordes', null, false),
('string', 'Guitare Soprano', null, false),
('string', 'Guitare acoustique', null, false),
('string', 'Guitare baryton', null, false),
('string', 'Guitare basse', null, false),
('string', 'Guitare classique', null, false),
('string', 'Guitare contra', null, false),
('string', 'Guitare à 12 cordes', null, false),
('string', 'Guitare à 7 cordes', null, false),
('string', 'Guitare électrique', null, false),
('percussion', 'Güiro', null, false),
('wood', 'Harmonica', null, false),
('wood', 'Harmonica Basse', null, false),
('wood', 'Harmonica Basse Hohner', null, false),
('wood', 'Harmonica Basse Huang', null, false),
('wood', 'Harmonica Chordet 20 trous', null, false),
('wood', 'Harmonica chromatique 12 trous', 'c', false),
('wood', 'Harmonica chromatique 14 trous', 'c', false),
('wood', 'Harmonica chromatique Ténor 12 trous', 'c', false),
('wood', 'Harmonica chromatique 12 trous', 'g', false),
('wood', 'Harmonica chromatique 16 trous', 'g', false),
('wood', 'Harmonica de verre', null, false),
('wood', 'Harmonica diatonique 10 trous', 'c', false),
('wood', 'Harmonica diatonique 10 trous', 'f', false),
('wood', 'Harmonica diatonique 10 trous', 'a', false),
('wood', 'Harmonica diatonique 10 trous', 'd', false),
('wood', 'Harmonica diatonique grave 10 trous', 'd', false),
('wood', 'Harmonica diatonique 10 trous', 'g', false),
('wood', 'Harmonica diatonique aigu 10 trous', 'g', false),
('wind', 'Harmonium', null, false),
('string', 'Harpe', null, false),
('wood', 'Hautbois', null, false),
('wood', 'Hautbois Baryton', null, false),
('wood', 'Hautbois Piccolo', null, false),
('wood', 'Hautbois baroque', null, false),
('wood', 'Hautbois d\'amour', null, false),
('wood', 'Hautbois de chasse', null, false),
('wood', 'Heckelphone', null, false),
('wood', 'Heckelphone Piccolo', null, false),
('voice', 'Hommes', null, false),
('wood', 'Horagai', null, false),
('brass', 'Hélicon', null, false),
('percussion', 'Kalimba', null, false),
('percussion', 'Kalimba Alto', null, false),
('percussion', 'Kalimba aigue', null, false),
('voice', 'Kazoo', null, false),
('wood', 'Kelhorn Alto', null, false),
('wood', 'Kelhorn Basse', null, false),
('wood', 'Kelhorn Soprano', null, false),
('wood', 'Kelhorn Soubasse', null, false),
('wood', 'Kelhorn Ténor', null, false),
('wood', 'Klaxon accordés', null, false),
('string', 'Koto', null, false),
('brass', 'Kuhlohorn', null, false),
('wood', 'Lupophone', null, false),
('string', 'Luth', null, false),
('string', 'Luth à 5 chœurs', null, false),
('string', 'Luth à 6 chœurs', null, false),
('string', 'Luth à 7 chœurs', null, false),
('string', 'Luth à 8 chœurs', null, false),
('string', 'Luth à 9 chœurs', null, false),
('string', 'Luth à 10 chœurs', null, false),
('string', 'Luth à 13 chœurs', null, false),
('string', 'Mandocello', null, false),
('string', 'Mandole', null, false),
('string', 'Mandole Alto', null, false),
('string', 'Mandole Ténor', null, false),
('string', 'Mandoline', null, false),
('string', 'Mandoline Octave', null, false),
('string', 'Mandoloncelle', null, false),
('percussion', 'Marimba', null, false),
('percussion', 'Marimba (double portée)', null, false),
('percussion', 'Marimba Contrebasse', null, false),
('percussion', 'Marimba basse', null, false),
('brass', 'Mellophone', null, false),
('voice', 'Mezzo-soprano', null, false),
('wood', 'Mélodica', null, false),
('percussion', 'Métallophone', null, false),
('string', 'Nyckelharpa', null, false),
('wood', 'Ocarina', null, false),
('wood', 'Ocarina Alto', 'c', false),
('wood', 'Ocarina Alto', 'f', false),
('wood', 'Ocarina Alto', 'b_flat', false),
('wood', 'Ocarina Alto', 'g', false),
('wood', 'Ocarina Basse', 'c', false),
('wood', 'Ocarina Soprano', 'c', false),
('wood', 'Ocarina Soprano', 'f', false),
('wood', 'Ocarina Soprano', 'b_flat', false),
('wood', 'Ocarina Soprano', 'g', false),
('wood', 'Octavin', null, false),
('', 'Ondes Martenot', null, false),
('brass', 'Ophicléide', null, false),
('brass', 'Ophicléide Alto', 'f', false),
('brass', 'Ophicléide Alto', 'e_flat', false),
('brass', 'Ophicléide Alto', 'b_flat', false),
('brass', 'Ophicléide Basse', 'c', false),
('brass', 'Ophicléide Contrebasse', 'e_flat', false),
('', 'Orgue', null, false),
('', 'Orgue Hammond', null, false),
('', 'Orgue percussif', null, false),
('', 'Orgue rotatif', null, false),
('', 'Orgue à anches', null, false),
('', 'Orgue à tuyaux', null, false),
('string', 'Oud', null, false),
('percussion', 'Papiers sablés', null, false),
('string', 'Pardessus de viole', null, false),
('percussion', 'Percussion', null, true),
('percussion', 'Percussions corporelles', null, false),
('percussion', 'Percussions de défilé', null, true),
('string', 'Piano', null, false),
('string', 'Piano Honky Tonk', null, false),
('string', 'Piano droit', null, false),
('', 'Piano jouet', null, false),
('string', 'Piano à queue', null, false),
('string', 'Piano électrique', null, false),
('percussion', 'Pierres', null, false),
('wood', 'Quena', null, false),
('wood', 'Quena', 'c', false),
('wood', 'Quena', 'f', false),
('wood', 'Quena', 'g', false),
('percussion', 'Quijada', null, false),
('wood', 'Rauschpfeife', null, false),
('wood', 'Rauschpfeife Sopranino', null, false),
('wood', 'Rauschpfeife Soprano', null, false),
('percussion', 'Roto', null, false),
('percussion', 'Rototoms', null, false),
('wood', 'Saqueboute alto', null, false),
('wood', 'Saqueboute basse', null, false),
('wood', 'Saqueboute ténor', null, false),
('brass', 'Sarrussophone', null, false),
('brass', 'Sarrussophone Alto', null, false),
('brass', 'Sarrussophone Baryton', null, false),
('brass', 'Sarrussophone Basse', null, false),
('brass', 'Sarrussophone Contrebasse', null, false),
('brass', 'Sarrussophone Sopranino', null, false),
('brass', 'Sarrussophone Soprano', null, false),
('brass', 'Sarrussophone Ténor', null, false),
('brass', 'Saxhorn', null, false),
('brass', 'Saxhorn alto', 'f', false),
('brass', 'Saxhorn alto', 'e_flat', false),
('wood', 'Saxophone', null, false),
('wood', 'Saxophone Alto', null, false),
('wood', 'Saxophone Baryton', null, false),
('wood', 'Saxophone Basse', null, false),
('wood', 'Saxophone C-Melody', null, false),
('wood', 'Saxophone Contrebasse', null, false),
('wood', 'Saxophone Sopranino', null, false),
('wood', 'Saxophone Sopranissimo', null, false),
('wood', 'Saxophone Soprano', null, false),
('wood', 'Saxophone Sub-Contrabasse', null, false),
('wood', 'Saxophone Ténor', null, false),
('wood', 'Saxophone mezzo-soprano', null, false),
('percussion', 'Scie musicale', null, false),
('wood', 'Serpent', null, false),
('percussion', 'Shaker', null, false),
('string', 'Shamisen', null, false),
('wood', 'Shehnai', null, false),
('wood', 'Sheng', null, false),
('wood', 'Sheng Alto', null, false),
('wood', 'Sheng Basse', null, false),
('wood', 'Sheng Soprano', null, false),
('wood', 'Sheng Ténor', null, false),
('wood', 'Sifflet à coulisse', null, false),
('string', 'Sitar', null, false),
('voice', 'Soprano', null, false),
('brass', 'Sousaphone', null, false),
('brass', 'Sousaphone', 'b_flat', false),
('percussion', 'Steeldrum', null, false),
('percussion', 'Steeldrum Alto', null, false),
('percussion', 'Steeldrum Basse', null, false),
('percussion', 'Steeldrum Cello', null, false),
('percussion', 'Steeldrum Guitar', null, false),
('percussion', 'Steeldrum Soprano', null, false),
('percussion', 'Steeldrum Ténor', null, false),
('', 'Synthétiseur', null, false),
('', 'Synthétiseur Goblins', null, false),
('', 'Synthétiseur New Age', null, false),
('', 'Synthétiseur Pad', null, false),
('', 'Synthétiseur Polyphonique', null, false),
('', 'Synthétiseur Sci-fi', null, false),
('', 'Synthétiseur brillant', null, false),
('', 'Synthétiseur chand', null, false),
('', 'Synthétiseur cristalin', null, false),
('', 'Synthétiseur d\'atmosphère', null, false),
('', 'Synthétiseur d\'effets', null, false),
('', 'Synthétiseur d\'instruments à cordes', null, false),
('', 'Synthétiseur d\'échos', null, false),
('', 'Synthétiseur de Sweep', null, false),
('', 'Synthétiseur de bande-son', null, false),
('', 'Synthétiseur de basses', null, false),
('', 'Synthétiseur de chœurs', null, false),
('', 'Synthétiseur de cordes frottées', null, false),
('', 'Synthétiseur de créneaux', null, false),
('', 'Synthétiseur de cuivres', null, false),
('', 'Synthétiseur de halo', null, false),
('', 'Synthétiseur de maillets', null, false),
('', 'Synthétiseur de percussions', null, false),
('', 'Synthétiseur de pluie', null, false),
('', 'Synthétiseur de sinusoïdes', null, false),
('', 'Synthétiseur de triangles', null, false),
('', 'Synthétiseur métallique', null, false),
('percusison', 'Tablas', null, false),
('percussion', 'Tam', null, false),
('percussion', 'Tam-Tam', null, true),
('percussion', 'Tambour de freins automobiles', null, false),
('percussion', 'Tambour militaire', null, false),
('percussion', 'Tambour sur cadre', null, false),
('percussion', 'Tambour à fente', null, false),
('percussion', 'Tambourin', null, false),
('percussion', 'Tambours ténor', null, false),
('wood', 'Taragote', null, false),
('percussion', 'Temple Blocks', null, false),
('string', 'Théorbe', null, false),
('', 'Thérémine', null, false),
('percussion', 'Timbales', null, true),
('percussion', 'Timbales latines', null, false),
('percussion', 'Timbre', null, false),
('wood', 'Tin Whistle', 'd', false),
('wood', 'Tin whistle', null, false),
('wood', 'Tin whistle', 'b_flat', false),
('percussion', 'Toms chinois', null, false),
('percussion', 'Toms de concert', null, false),
('percussion', 'Tonnerre en feuille', null, false),
('wood', 'Tournebout', null, false),
('wood', 'Tournebout Alto', null, false),
('wood', 'Tournebout Basse', null, false),
('wood', 'Tournebout Grande basse', null, false),
('wood', 'Tournebout Soprano', null, false),
('wood', 'Tournebout Ténor', null, false),
('wood', 'Traverso', null, false),
('percussion', 'Triangle', null, false),
('brass', 'Trombone', null, true),
('brass', 'Trombone alto', null, false),
('brass', 'Trombone basse', null, false),
('brass', 'Trombone contrebasse', null, false),
('brass', 'Trombone', 'b_flat', false),
('brass', 'Trombone soprano', null, false),
('brass', 'Trombone ténor', null, false),
('brass', 'Trompette', null, true),
('brass', 'Trompette baroque', null, false),
('brass', 'Trompette baroque', 'c', false),
('brass', 'Trompette baroque', 'f', false),
('brass', 'Trompette baroque', 'e_flat', false),
('brass', 'Trompette baroque', 'd', false),
('brass', 'Trompette baroque', 'b_flat', false),
('brass', 'Trompette basse', null, false),
('brass', 'Trompette basse', 'c', false),
('brass', 'Trompette basse', 'e_flat', false),
('brass', 'Trompette basse', 'b_flat', false),
('brass', 'Trompette de poche', null, false),
('brass', 'Trompette', 'c', false),
('brass', 'Trompette', 'f', false),
('brass', 'Trompette', 'a', false),
('brass', 'Trompette', 'e', false),
('brass', 'Trompette', 'e_flat', false),
('brass', 'Trompette', 'd', false),
('brass', 'Trompette', 'b_flat', true),
('brass', 'Trompette piccolo', null, false),
('brass', 'Trompette piccolo', 'a', false),
('brass', 'Trompette piccolo', 'b_flat', false),
('brass', 'Trompette ténor', null, false),
('brass', 'Trompette à coulisse', null, false),
('brass', 'Tuba', null, true),
('brass', 'Tuba Basse', 'f', false),
('brass', 'Tuba Basse', 'e_flat', false),
('brass', 'Tuba', 'c', false),
('brass', 'Tuba', 'f', false),
('brass', 'Tuba', 'e_flat', true),
('brass', 'Tuba', 'b_flat', true),
('brass', 'Tuba sous-contrebasse', null, false),
('brass', 'Tuba wagnérien', null, false),
('brass', 'Tuba wagnérien', 'f', false),
('brass', 'Tuba wagnérien', 'b_flat', false),
('brass', 'Tubaphone', null, false),
('percussion', 'Tubes d\'acier', null, false),
('voice', 'Ténor', null, false),
('string', 'Ukulélé', null, false),
('string', 'Ukulélé (Sol grave)', null, false),
('string', 'Ukulélé baryton', null, false),
('string', 'Ukulélé ténor', null, false),
('percussion', 'Verres musicaux', null, false),
('percussion', 'Vibraphone', null, true),
('string', 'Viole de gambe', null, false),
('string', 'Viole de gambe alto', null, false),
('string', 'Viole de gambe ténor', null, false),
('string', 'Violoncelle', null, false),
('string', 'Violoncelles', null, false),
('string', 'Violone', null, false),
('string', 'Violone', 'd', false),
('string', 'Violons', null, false),
('string', 'Virginal', null, false),
('wood', 'Vuvuzela', null, false),
('percussion', 'Wood Blocks', null, false),
('percussion', 'Xylomarimba', null, false),
('percussion', 'Xylophone', null, true);