instrument_index:
  path:   /instrument/
  controller: 'App\Controller\InstrumentController::index'
  methods: GET

instrument_show:
  path:   /instrument/{id}/show
  controller: 'App\Controller\InstrumentController::show'
  methods: GET

instrument_new:
  path:   /instrument/new
  controller: 'App\Controller\InstrumentController::new'
  methods: [GET, POST]

instrument_edit:
  path:   /instrument/{id}/edit
  controller: 'App\Controller\InstrumentController::edit'
  methods: [GET, POST]

instrument_delete:
  path:   /instrument/{id}/delete
  controller: 'App\Controller\InstrumentController::delete'
  methods: DELETE
