person_index:
  path:   /person/
  controller: 'App\Controller\PersonController::index'
  methods: GET

person_show:
  path:   /person/{id}/show
  controller: 'App\Controller\PersonController::show'
  methods: GET

person_new:
  path:   /person/new
  controller: 'App\Controller\PersonController::new'
  methods: [GET, POST]

person_edit:
  path:   /person/{id}/edit
  controller: 'App\Controller\PersonController::edit'
  methods: [GET, POST]

person_delete:
  path:   /person/{id}/delete
  controller: 'App\Controller\PersonController::delete'
  methods: DELETE
