program_index:
  path:   /program/
  controller: 'App\Controller\ProgramController::index'
  methods: GET

program_show:
  path:   /program/{id}/show
  controller: 'App\Controller\ProgramController::show'
  methods: GET

program_new:
  path:   /program/new
  controller: 'App\Controller\ProgramController::new'
  methods: [GET, POST]

program_edit:
  path:   /program/{id}/edit
  controller: 'App\Controller\ProgramController::edit'
  methods: [GET, POST]

program_delete:
  path:   /program/{id}/delete
  controller: 'App\Controller\ProgramController::delete'
  methods: DELETE
