status_index:
  path:   /status/
  controller: 'App\Controller\StatusController::index'
  methods: GET

status_new:
  path:   /status/new
  controller: 'App\Controller\StatusController::new'
  methods: [GET, POST]

status_edit:
  path:   /status/{id}/edit
  controller: 'App\Controller\StatusController::edit'
  methods: [GET, POST]

status_delete:
  path:   /status/{id}/delete
  controller: 'App\Controller\StatusController::delete'
  methods: DELETE
