y_soft_instrum:
  resource: "@YSoftInstrumBundle/Resources/config/routing.yml"
  prefix:   /

y_soft_login:
  path: /login
  defaults: { _controller: "YSoftInstrumBundle:Security:login" }
  methods:  [GET, POST]

y_soft_logout:
  path: logout
  methods: GET