<?php

namespace App\Repository;

/**
 * ConcertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConcertRepository extends \Doctrine\ORM\EntityRepository
{
    public function countAll()
    {
        $qb = $this->createQueryBuilder('c');
        $qb ->select($qb->expr()->count('c.id'));

        return $qb->getQuery()->getSingleScalarResult();
    }
}
