<?php

namespace App\Repository;

/**
 * MissingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MissingRepository extends \Doctrine\ORM\EntityRepository
{
}
