band_index:
    path:     /
    defaults: { _controller: "YSoftInstrumBundle:Band:index" }
    methods:  GET

band_show:
    path:     /{id}/show
    defaults: { _controller: "YSoftInstrumBundle:Band:show" }
    methods:  GET

band_new:
    path:     /new
    defaults: { _controller: "YSoftInstrumBundle:Band:new" }
    methods:  [GET, POST]

band_edit:
    path:     /{id}/edit
    defaults: { _controller: "YSoftInstrumBundle:Band:edit" }
    methods:  [GET, POST]

band_delete:
    path:     /{id}/delete
    defaults: { _controller: "YSoftInstrumBundle:Band:delete" }
    methods:  DELETE
