concert_index:
    path:     /
    defaults: { _controller: "YSoftInstrumBundle:Concert:index" }
    methods:  GET

concert_show:
    path:     /{id}/show
    defaults: { _controller: "YSoftInstrumBundle:Concert:show" }
    methods:  GET

concert_new:
    path:     /new
    defaults: { _controller: "YSoftInstrumBundle:Concert:new" }
    methods:  [GET, POST]

concert_edit:
    path:     /{id}/edit
    defaults: { _controller: "YSoftInstrumBundle:Concert:edit" }
    methods:  [GET, POST]

concert_delete:
    path:     /{id}/delete
    defaults: { _controller: "YSoftInstrumBundle:Concert:delete" }
    methods:  DELETE