person_index:
    path:     /
    defaults: { _controller: "YSoftInstrumBundle:Person:index" }
    methods:  GET

person_show:
    path:     /{id}/show
    defaults: { _controller: "YSoftInstrumBundle:Person:show" }
    methods:  GET

person_new:
    path:     /new
    defaults: { _controller: "YSoftInstrumBundle:Person:new" }
    methods:  [GET, POST]

person_edit:
    path:     /{id}/edit
    defaults: { _controller: "YSoftInstrumBundle:Person:edit" }
    methods:  [GET, POST]

person_delete:
    path:     /{id}/delete
    defaults: { _controller: "YSoftInstrumBundle:Person:delete" }
    methods:  DELETE
