publisher_index:
    path:     /
    defaults: { _controller: "YSoftInstrumBundle:Publisher:index" }
    methods:  GET

publisher_show:
    path:     /{id}/show
    defaults: { _controller: "YSoftInstrumBundle:Publisher:show" }
    methods:  GET

publisher_new:
    path:     /new
    defaults: { _controller: "YSoftInstrumBundle:Publisher:new" }
    methods:  [GET, POST]

publisher_edit:
    path:     /{id}/edit
    defaults: { _controller: "YSoftInstrumBundle:Publisher:edit" }
    methods:  [GET, POST]

publisher_delete:
    path:     /{id}/delete
    defaults: { _controller: "YSoftInstrumBundle:Publisher:delete" }
    methods:  DELETE
