size_index:
    path:     /
    defaults: { _controller: "YSoftInstrumBundle:Size:index" }
    methods:  GET

size_show:
    path:     /{name}/show
    defaults: { _controller: "YSoftInstrumBundle:Size:show" }
    methods:  GET

size_new:
    path:     /new
    defaults: { _controller: "YSoftInstrumBundle:Size:new" }
    methods:  [GET, POST]

size_edit:
    path:     /{name}/edit
    defaults: { _controller: "YSoftInstrumBundle:Size:edit" }
    methods:  [GET, POST]

size_delete:
    path:     /{name}/delete
    defaults: { _controller: "YSoftInstrumBundle:Size:delete" }
    methods:  DELETE
