<?php

namespace YSoft\InstrumBundle\Repository;

/**
 * InstrumentationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstrumentationRepository extends \Doctrine\ORM\EntityRepository
{
}
