#index:
#  path: /
#  controller: App\Controller\DefaultController::index

login:
  path: /login
  defaults: { _controller: 'App\Controller\SecurityController::login' }
  methods:  [GET, POST]

logout:
  path: logout
  methods: GET

ajax_upload:
  path: /upload
  defaults: { _controller: 'App\Controller\FileController::ajaxUpload' }
  methods: [POST]
  condition: "request.isxmlHttpRequest()"

file_download:
  path: /download/{file}
  defaults: { _controller: 'App\Controller\FileController::download' }
  methods: [GET]
  requirements:
    file: .+