#index:
#  path: /
#  controller: App\Controller\DefaultController::index

login:
  path: /login
  controller: 'App\Controller\SecurityController::login'
  methods:  [GET, POST]

logout:
  path: logout
  methods: GET

instructions:
  path: /instructions
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: instructions.html.twig

ajax_upload:
  path: /upload
  controller: 'App\Controller\FileController::ajaxUpload'
  methods: [POST]
  condition: "request.isxmlHttpRequest()"

file_download:
  path: /download/{file}
  controller: 'App\Controller\FileController::download'
  methods: [GET]
  requirements:
    file: .+