y_soft_instrum_concert:
  resource: "@YSoftInstrumBundle/Resources/config/routing/concert.yml"
  prefix:   /concert

y_soft_instrum_type:
  resource: "@YSoftInstrumBundle/Resources/config/routing/type.yml"
  prefix:   /type


y_soft_instrum_publisher:
  resource: "@YSoftInstrumBundle/Resources/config/routing/publisher.yml"
  prefix:   /publisher

y_soft_instrum_instrumentation:
  resource: "@YSoftInstrumBundle/Resources/config/routing/instrumentation.yml"
  prefix:   /instrumentation

y_soft_instrum_person:
  resource: "@YSoftInstrumBundle/Resources/config/routing/person.yml"
  prefix:   /person

y_soft_instrum_size:
  resource: "@YSoftInstrumBundle/Resources/config/routing/size.yml"
  prefix:   /size

y_soft_instrum_status:
  resource: "@YSoftInstrumBundle/Resources/config/routing/status.yml"
  prefix:   /status

y_soft_instrum_missing:
  resource: "@YSoftInstrumBundle/Resources/config/routing/missing.yml"
  prefix:   /missing

y_soft_instrum_piece:
  resource: "@YSoftInstrumBundle/Resources/config/routing/piece.yml"