y_soft_instrum_program:
  resource: "@YSoftInstrumBundle/Resources/config/routing/program.yml"
  prefix:   /program

y_soft_instrum_concert:
  resource: "@YSoftInstrumBundle/Resources/config/routing/concert.yml"
  prefix:   /concert

y_soft_instrum_type:
  resource: "@YSoftInstrumBundle/Resources/config/routing/type.yml"
  prefix:   /type

y_soft_instrum_publisher:
  resource: "@YSoftInstrumBundle/Resources/config/routing/publisher.yml"
  prefix:   /publisher

y_soft_instrum_instrumentation:
  resource: "@YSoftInstrumBundle/Resources/config/routing/instrumentation.yml"
  prefix:   /instrumentation

y_soft_instrum_person:
  resource: "@YSoftInstrumBundle/Resources/config/routing/person.yml"
  prefix:   /person

y_soft_instrum_size:
  resource: "@YSoftInstrumBundle/Resources/config/routing/size.yml"
  prefix:   /size

y_soft_instrum_status:
  resource: "@YSoftInstrumBundle/Resources/config/routing/status.yml"
  prefix:   /status

y_soft_instrum_missing:
  resource: "@YSoftInstrumBundle/Resources/config/routing/missing.yml"
  prefix:   /missing

y_soft_instrum_band:
  resource: "@YSoftInstrumBundle/Resources/config/routing/band.yml"
  prefix: /band

y_soft_instrum_lending:
  resource: "@YSoftInstrumBundle/Resources/config/routing/lending.yml"
  prefix: /lending

y_soft_instrum_piece:
  resource: "@YSoftInstrumBundle/Resources/config/routing/piece.yml"

y_soft_instrum_instrument:
  resource: "@YSoftInstrumBundle/Resources/config/routing/instrument.yml"
  prefix:   /instrument

y_soft_instrum_part:
  resource: "@YSoftInstrumBundle/Resources/config/routing/part.yml"
  prefix:   /part

#y_soft_instrum_upload:
#  path: /upload
#  defaults: { _controller: "YSoftInstrumBundle:File:upload" }
#  methods: [POST]

y_soft_instrum_ajax_upload:
  path: /upload
  defaults: { _controller: "YSoftInstrumBundle:File:ajaxUpload" }
  methods: [POST]
  condition: "request.isxmlHttpRequest()"