YSoft\InstrumBundle\Entity\Band:
  type: entity
  table: null
  repositoryClass: YSoft\InstrumBundle\Repository\BandRepository
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 255
      unique: true

  oneToMany:
    lendings:
      targetEntity: YSoft\InstrumBundle\Entity\Lending
      mappedBy: band

  lifecycleCallbacks: {  }