YSoft\InstrumBundle\Entity\Concert:
  type: entity
  table: null
  repositoryClass: YSoft\InstrumBundle\Repository\ConcertRepository
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 255
      unique: true
    date:
      column_name: "`date`"
      type: datetime

  manyToMany:
    pieces:
      targetEntity: YSoft\InstrumBundle\Entity\Piece
      cascade:
        - persist
        - remove
      inversedBy: concerts
      joinTable:
        name: concert_piece
        joinColumns:
          program_id:
            referencedColumnName: id
            onUpdate: cascade
            onDelete: cascade
        inverseJoinColumns:
          piece_id:
            referencedColumnName: id
            onUpdate: cascade
            onDelete: cascade

  lifecycleCallbacks: {  }