YSoft\InstrumBundle\Entity\Instrument:
  type: entity
  repositoryClass: YSoft\InstrumBundle\Repository\InstrumentRepository
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO

  fields:
    name:
      type: string
      length: 255
    key:
      column: "`key`"
      type: string
      length: '7'
      nullable: true
    family:
      type: string
      length: '15'
      nullable: true
    common:
      type: boolean

  oneToMany:
    parts:
      targetEntity: YSoft\InstrumBundle\Entity\Part
      mappedBy: instrument
      fetch: EXTRA_LAZY
      orphanRemoval: true
      cascade:
        - persist

  lifecycleCallbacks: {  }