YSoft\InstrumBundle\Entity\Lending:
  type: entity
  table: null
  repositoryClass: YSoft\InstrumBundle\Repository\LendingRepository
  entityListeners:
    YSoft\InstrumBundle\Listener\LendingListener:
      prePersist: [ changeLendingPiecesStatus ]
      preUpdate: [ changeLendingPiecesStatus ]
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    contact:
      type: string
      length: 255
    start:
      type: date
    end:
      type: date
      nullable: true
    ours:
      type: boolean

  manyToOne:
    band:
      targetEntity: YSoft\InstrumBundle\Entity\Band
      inversedBy: lendings

  manyToMany:
    pieces:
      targetEntity: YSoft\InstrumBundle\Entity\Piece
      inversedBy: lendings
      cascade:
        - persist
      joinTable:
        name: piece_move
      
  lifecycleCallbacks: {  }