YSoft\InstrumBundle\Entity\Part:
  type: entity
  repositoryClass: YSoft\InstrumBundle\Repository\PartRepository
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO

  fields:
    clef:
      type: string
      length: '3'
      nullable: true
    number:
      type: integer
      nullable: true
    solo:
      type: boolean
    file:
      type: string
      nullable: true

  manyToOne:
    instrument:
      targetEntity: YSoft\InstrumBundle\Entity\Instrument
      inversedBy: parts
    piece:
      targetEntity: YSoft\InstrumBundle\Entity\Piece
      inversedBy: parts

  lifecycleCallbacks: {  }