YSoft\InstrumBundle\Entity\Piece:
  type: entity
  table: null
  repositoryClass: YSoft\InstrumBundle\Repository\PieceRepository
  id:
    id:
      type: float
      id: true
      generator:
        strategy: AUTO

  fields:
    name:
      type: string
      length: 255
    translation:
      type: string
      length: 255
      nullable: true
    level:
      type: float
      nullable: true
    year:
      type: smallint
      nullable: true
    reference:
      type: string
      length: 255
      nullable: true
      unique: true
    note:
      type: text
      nullable: true
    createdAt:
      type: datetime
      gedmo:
        timestampable:
          on: create

  oneToMany:
    movements:
      targetEntity: YSoft\InstrumBundle\Entity\Piece
      mappedBy: work
      cascade:
        - persist
    parts:
      targetEntity: YSoft\InstrumBundle\Entity\Part
      mappedBy: piece
      fetch: EXTRA_LAZY
      orphanRemoval: true
      cascade:
        - persist
      orderBy:
        solo: DESC
        instrument: ASC
        number: ASC
    missings:
      targetEntity: YSoft\InstrumBundle\Entity\Missing
      mappedBy: piece
      fetch: EXTRA_LAZY
      orphanRemoval: true
      cascade:
        - persist

  manyToOne:
    publisher:
      targetEntity: YSoft\InstrumBundle\Entity\Publisher
      inversedBy: pieces
      cascade:
        - persist
        - remove
    size:
      targetEntity: YSoft\InstrumBundle\Entity\Size
      inversedBy: pieces
      cascade:
        - persist
      joinColumn:
        name: size
        referencedColumnName: name
    status:
      targetEntity: YSoft\InstrumBundle\Entity\Status
      inversedBy: pieces
      cascade:
        - persist
    instrumentation:
      targetEntity: YSoft\InstrumBundle\Entity\Instrumentation
      inversedBy: pieces
      cascade:
        - persist
    type:
      targetEntity: YSoft\InstrumBundle\Entity\Type
      inversedBy: pieces
      cascade:
        - persist
    program:
      targetEntity: YSoft\InstrumBundle\Entity\Program
      inversedBy: pieces
      orderBy: { updatedAt: 'DESC' }
    work:
      targetEntity: YSoft\InstrumBundle\Entity\Piece
      inversedBy: movements
      orderBy: { id: 'ASC' }

  manyToMany:
    composers:
      targetEntity: YSoft\InstrumBundle\Entity\Person
      inversedBy: compositions
      cascade:
        - persist
      joinTable:
        name: piece_composer
    arrangers:
      targetEntity: YSoft\InstrumBundle\Entity\Person
      inversedBy: arrangements
      cascade:
        - persist
      joinTable:
        name: piece_arranger
    concerts:
      targetEntity: YSoft\InstrumBundle\Entity\Concert
      mappedBy: pieces
      orderBy: { "date": 'DESC' }
    lendings:
      targetEntity: YSoft\InstrumBundle\Entity\Lending
      mappedBy: pieces
      orderBy: { start: DESC }

  lifecycleCallbacks: {  }