YSoft\InstrumBundle\Entity\Publisher:
  type: entity
  table: null
  repositoryClass: YSoft\InstrumBundle\Repository\PublisherRepository
  id:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 255
      unique: true
    note:
      type: text
      nullable: true

  oneToMany:
    pieces:
      targetEntity: YSoft\InstrumBundle\Entity\Piece
      mappedBy: publisher

  lifecycleCallbacks: {  }