YSoft\InstrumBundle\Entity\Status:
  type: entity
  table: null
  repositoryClass: YSoft\InstrumBundle\Repository\StatusRepository
  id:
    id:
      type: string
      id: true
      generator: ~
  fields:
    name:
      type: string
      length: 255

  oneToMany:
    pieces:
      targetEntity: YSoft\InstrumBundle\Entity\Piece
      mappedBy: status
      
  lifecycleCallbacks: {  }